# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yingdong Zhang
motto: Pursue excellence and success will follow.
email: daniel.ydzhang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yingdong Zhang's Personal Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yingdongzhang.github.io/" # the base hostname & protocol for your site
twitter_username: Daniel_Yingdong
github_username:  yingdongzhang
categories: ["post", ".NET", "diary", "中文"]

# Build settings
markdown: kramdown
